# Generated by Django 3.0.3 on 2020-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=30)),
                ('report', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
